Update api.yml

diff --git a/.github/workflows/api.yml b/.github/workflows/api.yml
--- a/.github/workflows/api.yml
+++ b/.github/workflows/api.yml
@@ -1,8 +1,15 @@
-name: post-api
-on: push
+name: git diff api
+on: pull_request
 jobs:
   my-job:
     runs-on: ubuntu-latest
     steps:
       - name: my-step
-        run: echo $GITHUB_API_URL $GITHUB_REPOSITORY
+        run: |
+          set +e # dont fail based on grep exit code
+          git diff --name-only HEAD~1 | grep --invert-match '.md$'
+          if [ $? -eq 0 ]; then
+              echo "docs_only=false" >> $GITHUB_OUTPUT
+          else
+              echo "docs_only=true" >> $GITHUB_OUTPUT
+          fi
